### ISSUE TITLE
Withdrawing Profits?

### ISSUE THREAD

**Issue by octas** [paco0x/amm-arbitrageur#12]
Hey, 
Thanks for the awesome project!

I've modified the bot a bit to increase chances of profit.
It did report a profit of +$100 and showed a transaction hash. 
But I can't find the money anywhere. 
The contract value on bscscan is saying $0.01. 

I tried creating a simple script: 
`    const res = await flashBot.withdraw();
    const receipt = await res.wait(1);
    log.debug(`Transaction: ${receipt.transactionHash}`);`

But nothing is received, not even a transcation hash. 

Any idea what could the problem be?

**Comment by paco0x** [comment]
This may be caused by the latency. The bot found a possible profit of $100 and send a transaction to do arbitrage. But the transaction needs some time to be processed and packaged to the new block. During this time, some other bots in the network may also trying to do arbitrage. If they are faster than you, then the profit may be taken by other bots.

Suggestions: You may need to optimize the bot codes to respond more quickly. You may need to use a higher gas fee so your tx gets handled more quickly than others. There are always competitions between the bots.

**Comment by octas** [comment]
Thanks for the quick reply. Can you point me to the areas in the code that I can optimize?

**Comment by paco0x** [comment]
For example: Use your own node or a private node to get low latency on network requests. Use a higher gas fee so your tx gets processed quickly. Update the token list to monitor some other token that other bots may not be monitoring. Or use other networks because too many bots are running on BSC and ETH. You may figure out more ways to optimize it by yourself.

**Comment by octas** [comment]
I really appreciate your answers, they've been really helpful. 
I have one more question, I added tokens to tokens.ts and token pairs to bsc-pairs.json. However, they're still not loaded or used by the bot. When I output the debug in the console, the only pairs considered are the ones you originally included. 
It complains about "no base tokens in pair" I did update the base tokens in the contract and now have more than bnb as the base token, but the problem persists.

**Comment by paco0x** [comment]
There's a bug in early code. It uses the deployer's address as the BASE TOKEN address. It got fixed in https://github.com/paco0x/amm-arbitrageur/commit/d38d04a8d81392f27fe77cd01581663f0103cb4d.

So the easy solution for this issue is: use the latest code and redeploy the contract.

Or if you've read the contract code. You may notice that there are some functions to edit and show the current base token lists in the contract. You can use `addBaseToken`, `removeBaseToken` and `getBaseTokens` to interact with the contact.

Make sure WBNB or WETH is in the base token list. You can also add other tokens also as USDC/USDT/BUSD/BTC to the base token list.

**Comment by octas** [comment]
Hi thanks for the quick reply. 
I did actually use the addBaseToken to add a list of base tokens, and I checked that they're actually added by calling getBaseTokens.
And I made sure to use the latest version of the code. Still no luck. My base tokens now has all BUSD/USDT/WBNB. 

The other thing, what's the difference between the token list in tokens.ts, and the pairs list in bsc-pairs.json? Do the tokens on the tokens.ts list get paired up automatically with base tokens? Cause I only see the bsc-pairs.json pairs being used. 

Last thing, I did add more DEX factories addresses to the tokens.ts list, but I also don't think they're being used. 

I know it's a lot of questions, I really appreciate your time and effort you put on this project.

**Comment by paco0x** [comment]
> Hi thanks for the quick reply.
> I did actually use the addBaseToken to add a list of base tokens, and I checked that they're actually added by calling getBaseTokens.
> And I made sure to use the latest version of the code. Still no luck. My base tokens now has all BUSD/USDT/WBNB.
> 
> The other thing, what's the difference between the token list in tokens.ts, and the pairs list in bsc-pairs.json? Do the tokens on the tokens.ts list get paired up automatically with base tokens? Cause I only see the bsc-pairs.json pairs being used.
> 
> Last thing, I did add more DEX factories addresses to the tokens.ts list, but I also don't think they're being used.
> 
> I know it's a lot of questions, I really appreciate your time and effort you put on this project.

Please refer to https://github.com/paco0x/amm-arbitrageur#how-can-i-change-the-token-pairs-the-bot-is-monitoring

**Comment by octas** [comment]
That was very helpful! I was able to get it working with all new pairs and dexes. 
Still haven't been able to get it to actually perform a flash swap, it always fails, either "execution reverted" or "arbitrage fail, no profit".
Experimented with different gas prices, and various exchanges. No luck. It was a great learning experience though, and I really appreciate you posting this project.

**Comment by octas** [comment]
If you do have any suggestions on how to solve the problem above, I'd really appreciate if you share them.
